### ISSUE TITLE
examples combines @from with @notAfter

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#1331]
We have a single example (used twice with slight differences) that demonstrates use of `@notAfter` to indicate the imprecise end of a duration; however, `@notAfter` is not intended for indicating a duration.

```
  <residence from="1857-03-01" notAfter="1857-04-30">From the 1st
    of March to some time in April of 1857.</residence>
```

See thread “bad date example” on TEI Council mailing list, starting 2015-05-25.

Original comment by: @sydb

**Comment by jamescummings** [comment]
We should update the prose to have examples of doing this. It is clear to me at least that as soon as you have @from or @to you have a duration and the other notBefore/notAfter then applies to the imprecision of the missing from/to attribute.

**Comment by jamescummings** [comment]
Full council agrees, and tells Syd to update the prose, pointing Council to a draft.

**Comment by sydb** [comment]
While there is still further work to do in this area, this particular ticket has been addressed.

**Comment by hcayless** [comment]
1) The example immediately following the table contradicts the information in the table in <http://teic.github.io/TEI/ND.html#NDATTSda>, because it has `@from`, `@notBefore`, and `@notAfter`. 

2) Also, there's a French [example](https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/att.datable.w3c.xml#L91) that uses `@when` in conjunction with `@notBefore` and `@notAfter`. I've switched the checks that enforce usage as outlined in the table to warnings, but we must fix `#1` and we should either remove the example in `#2` or change our minds about whether it's ok.

**Comment by sydb** [comment]
1) I disagree, although I see how one might think that. The table only discusses combinations of 2 attributes from att.datable.w3c (and not even those in att.datable.iso or att.datable.custom, as they can cause much more confusion because the standard representation can include the representation of a duration). The example shows a 3-attribute combination. But obviously the importance of that difference is not made at all clear, so I think we need to make this more obvious. Perhaps adding a heading to the table (“2-attr combos”) and beef up the prose of the paragraph following so it is clear that it is referring to 3-attr combos.

2) Oh dear. Well spotted. I don’t read French, so I don’t know if the example is correct or not. (Many people misuse `--12-11` to mean “some 11th of Dec, not sure which” when what it means is “every 11th of Dec”. (See the [definition of gMonthDay](https://www.w3.org/TR/xmlschema-2/#gMonthDay), e.g.)) But whether this particular example is correct or not, it seems perfectly reasonable that `<date when="--12-11" notBefore="1699-12-31" notAfter="1799-12-31">` would mean “every 11th of Dec in the 1700s”. (Which, of course, is not often what a humanist wants to say — more often, it seems to me, a humanist wants to say “some 11th of Dec in the 1700s”, but that’s not possible with att.datable.w3c, and is one of the reasons I think we need to seriously consider att.datable.loc. :-)

**Comment by lb42** [comment]
I think the fr example is trying to be too clever. It provides two normalisations of the date "11 decembre 17..", one using @when, the other using the combination of @notBefore and @notAfter. Either on its own
would be fine, but both together is needlessly confusing. I'd suggest simply removing the @when one, since we've already got examples of that way of indicating an imprecise date.

**Comment by hcayless** [comment]
The usage of `@notBefore` also contradicts the attribute's definition: "specifies the earliest possible date for the event"; not "specifies the earliest possible date for the beginning or end of the event". I don't think it can be used the way you're using it in the example. It's a good example though. We should figure out how to encode it properly.

**Comment by hcayless** [comment]
I think we have to get rid of the example immediately after the table or redefine `@notBefore` and `@notAfter`. This is a release blocker in my opinion.

Could the table not be simplified thusly:

  | `@notBefore` | `@from`
-------|-----------------|------------------
`@notAfter` | range within which an event took place, inclusive | duration beginning at `@from` and ending some time before `@notAfter`, inclusive
`@to` | duration beginning at or after `@notBefore` and ending at `@to`, inclusive | duration from `@from` to `@to`, inclusive

**Comment by hcayless** [comment]
Since we seem stalled on this, and I'm extremely reluctant to release it in this state, I've pared down the prose and removed the example with `@from`, `@notBefore`, and `@notAfter`. We can discuss this further when we have more time.

**Comment by sydb** [comment]
[Responding to Hugh’s post 3 days ago about simplifying the table.]

I personally agree that removing “support” for the 3-attr combinations or redefining `@notBefore` and `@notAfter` so they make more sense is a good idea. Not sure it’s release-blocking, but certainly in favor.

As for the table, yes it could (and perhaps should) be simplified as you propose. If my complete re-take on the table (below) is not adopted, I would probably be in favor of your simplified version. But it fails to address the idea pushed by I forget who (Peter? James?) that, say, `@from` and `@notBefore` should not be used as a 2-attribute combination.

New take on table, first allowing 3-attr combos (as someone on list was suggesting), second disallowing them:

attribute combination | implies
----------------------|--------
`@from`, `@to`	      | a duration starting at `@from` and continuing to `@to`, inclusive
`@notBefore`, `@notAfter` | occured sometime within the range between `@notBefore` and `@notAfter`, inclusive
`@from`, `@notAfter`      | a duration starting at `@from` and continuing to some time before `@notAfter`, inclusive
`@notBefore`, `@to`	      | a duration starting sometime after `@notBefore` and continuing to `@to`, inclusive
`@from`, `@notBefore`, `@notAfter` | a duration starting at `@from` and continuing to some time between `@notBefore` and `@notAfter`, inclusive
`@notBefore`, `@notAfter`, `@to`   | a duration starting some time between `@notBefore` and `@notAfter`, and continuing to `@to`, inclusive
`@from`, `@notBefore`     | _no agreed upon semantics_
`@to`, `@notAfter`        | _no agreed upon semantics_
`@when` with **any of `@notAfter`, `@notBefore`, `@from`, `@to`** | _no agreed upon semantics_

------------------------
the **above with, below without** 3-attr combinations

-------------------------

attribute combination | implies
----------------------|--------
`@from`, `@to`	      | a duration starting at `@from` and continuing to `@to`, inclusive
`@notBefore`, `@notAfter` | occured sometime within the range between `@notBefore` and `@notAfter`, inclusive
`@from`, `@notAfter`      | a duration starting at `@from` and continuing to some time before `@notAfter`, inclusive
`@notBefore`, `@to`	      | a duration starting sometime after `@notBefore` and continuing to `@to`, inclusive
`@from`, `@notBefore`     | _no agreed upon semantics_
`@to`, `@notAfter`        | _no agreed upon semantics_
any combination of 3 or more attribute from this class |  _no agreed upon semantics_
`@when` with any other attribute from this class | _no agreed upon semantics_

**Comment by hcayless** [comment]
I'm not against the 3-attribute idea, but maintain we'd have to change the @notBefore/@notAfter definitions to make it work.

**Comment by sydb** [comment]
[Responding to Hugh's next post — is there any way to get GitHub to put a timestamp on these, rather than an imprecise relative date?]

Looks like there's a copy-and-paste error in your tidied up prose, Hugh — part of it is gibberish. I should be able to hit this tomorrow if you haven’t, but will be away from net for most of today.

**Comment by hcayless** [comment]
Fixed it. If you hover over the relative date, it'll show you the absolute one.

**Comment by sydb** [comment]
> If you hover over the relative date [GitHub provides for a post], it'll show you the absolute one.

Ah! Thank you. I see you've fixed the prose error. Now we have to decide what to do about Peter's proposal that we not allow `@when` and any of the other att.datable.w3c attrs, and our own French example that gives an example of that. (Note that our own Schematron now flags that example with a warning.)
Lou on 2016-03-16 22:00Z suggests that “the fr example is trying to be too clever”. I think he is right. But Lou’s further analisys that it “provides two normalisations …, one using `@when`, the other using the combination of `@notBefore` and `@notAfter`” seems to me to fall short. It’s not that the example provides two separate normalizations, but rather that it uses two separate mechanisms to provide normalization. Here’s the example again:
~~~~~xml
<dateline>
  <placeName>Paris,</placeName>, ce <date when="--12-11"
   notBefore="1699-12-31" notAfter="1799-12-31">11 décembre 17.. </date>
 </dateline>
~~~~~
I am not sure what the encoder meant by “17..”. She most likely means that the source document contained a seventeen followed by two dots; but she might have meant the source document contained a 4-digit year, of which only the first two could be read. (In which case she should have used `<gap>` :-) Doesn’t matter much. Either way, the `@when` normalizes the “11th of Dec” bit, and the combination of `@notBefore` and `@notAfter` narrow down the range of possible choices to those dates for which the year starts with a “17”. So it’s not the case that “Either on its own
would be fine”. Just the `@when` on its own normalizes “11 décembre 17.. ” to every December 11th ever, and just `@notBefore` and `@notAfter` (as Lou suggests we change it to) would normalize that string to “Some date for which the year starts with ‘17’, i.e. some day in 1700-01-01 to 1799-12-31, inclusive”. Neither seems satisfactory.
But worse, as I indicated above, the combination of `@when`, `@notBefore`, and `@notAfter` is probably not satisfactory, either. It suggests that the letter was written on each of the 100 11ths of December that occurred in 1700s, **not** a single 11th of December, we just don’t know which one.
Given that this example has been around for years if not decades, and the Schematron check is brand new and does not have significant discussion backing it up (although neither does the example), that we should remove the Schematron check before release.

**Comment by lb42** [comment]
I think you're making needlessly heavy weather of this. The French example is not exemplary, for whatever reason, and should be removed in its entirety. Yes it's been there a long time, but it's still not right: a corrigible error in fact. The schematron rule may be new, but so are most of them. It enforces a sensible prohibition already implicit in the text (if you provide @when you are supplying a specific date, so it makes no sense to provide the other attributes as well). It should remain.

**Comment by ebeshero** [comment]
Actually, having just read Syd's analysis of the French example, I very much like the idea to correct it, simply by removing the @when which is the attribute that makes no sense. As an example of why and how to use @notBefore and @notAfter, it otherwise makes a lot of sense to me. Could we correct it before release as Syd is describing?

Elisa


Typeset by hand on my iPad

**Comment by lb42** [comment]
True, but (without the @when)  it doesn't add anything to examples using @notBefore and @notAfter which are already there.

More significantly, I think the other French example in this document is also wrong

        <egXML xmlns="http://www.tei-c.org/ns/Examples" source="#fr-ex-Ormesson-douane">Shakespeare meurt dix jours plus tard, à Stratford-on-Avon, Warwickshire, dans
          l'Angleterre protestante et dans le calendrier julien, le <date calendar="#Julian" when="--04-23">mardi 23 avril ancien style</date>, c'est-à-dire le <date calendar="#Gregorian" when="--04-23">3 mai</date> dans le calendrier grégorien. </egXML>

The second date specifies that it is using the Gregorian calendar, so surely its @when should read "--05-03"  ?

**Comment by sydb** [comment]
@ebeshero : I may not have been clear on it, but that was not my intent. I think if we just remove `@when` from that example, the result is kinda useless.

So if Lou (who understands French) thinks that example should be removed, I’m all in favor and have just removed it (and the corresponding BIB entry) from the GLs.

As for the other French example Lou flags (which immediately preceded the one just deleted), @lb42 I think you are correct it is also wrong, but I’m pretty sure **both** of the `@when` values should be `"--05-03"`, as the value of `@when` is *definitionally* Gregorian or proleptic Gregorian no matter what the content is. (Which is why `@calendar` tells you what calendar to use interpreting the _content_, but not the attrs; at least not the W3C and ISO attrs — you get to do what you want with the custom attrs, I suppose.)

So I’ve also updated that example (fixing the whitespace along the way) as a separate commit. I updated the `@versionDate`, too, but I’m not sure I should have. Although this is a significant change, it does not pertain to the translation. In any caes, @lb42 , could you check that example and make sure I haven’t messed up the French?

**Comment by martindholmes** [comment]
@sydb: the calendar used for values in the `@*-custom` attributes is declared using `@datingMethod`.

**Comment by sydb** [comment]
Council decides to make GREEN for assignee to go ahead and update prose and insert list (w/ 3-attr combos), but wants those that are “no agreed upon semantics” to be out of the table, and instead the prose to just say that they don’t make sense and are not allowed.

**Comment by martindholmes** [comment]
What exactly is now not allowed? I use all sorts of combinations of these attributes for perfectly rational reasons (according to me).

**Comment by sydb** [comment]
Martin —

The combinations described above as “no agreed upon semantics”, i.e.:

- `@from` and `@notBefore`
- `@to` and `@notAfter`
- `@when` with **any** of `@notAfter`, `@notBefore`, `@from`,  or `@to`

**Comment by martindholmes** [comment]
The first two in the list are a bit odd, but the last surely might be combined with certainty and precision elements pointing at the `@when`, so that you could specify with low precision and/or certainty that something happened at a particular `@when`, but that you're also confident that it didn't happen before point X or after point Y. That seems perfectly logical to me.

**Comment by sydb** [comment]
Well, @martindholmes, I don’t claim to have a strong opinion on this, but Council was pretty clear at the face-to-face that
a) `@when` should not be combined with `@notAfter`, `@notBefore`, `@from`, or `@to`, and
b) the _Guidelines_ should say so in prose, but not in the table of values nor in a Schematron constraint

Your idea of something like
~~~~~xml
    <certainty locus="value" target="#e1" match="@when" degree="0.3"/>
    <certainty locus="value" target="#e1" match="@notBefore" degree="0.9"/>
    <certainty locus="value" target="#e1" match="@notAfter" degree="0.9"/>
    <!-- ... -->
    <event xml:id="e1" when="2016-06-01" notBefore="2016-04-15" notAfter="2016-07-04">
~~~~~~
To indicate “Event 'e1' probably occurred on or about the 1st of June, but most certainly after tax day (USA) and before Independance day (USA)” does seem plausible, if quite improbable.

**Comment by martindholmes** [comment]
I just validated some documents with a newly-built schema using the current dev branch, and all of a sudden a lot of structures like this are invalid:

~~~~~
<biblStruct>
               <monogr>
                  <title>A femme désolée mari ioyeux</title><title type="trunc">A femme désolée mari ioyeux</title>
                  <idno>Bibliothèque Nationale de France cote Te22, p. fol. (p. 44), cliché 68-B-46294.</idno>
                  <imprint>
                     <publisher>Nicolas Guérard</publisher>
                     <pubPlace>Paris</pubPlace>
                     <date xml:id="creationDate" when="1700" notBefore="1695" notAfter="1705">1695-1705</date>
                     <certainty target="#creationDate" degree="0.5"/>
                  </imprint>
               </monogr>
               <note>Image dimensions 2023 x 3042.</note></biblStruct>
~~~~~

I don't think there's anything wrong with this, and I don't think the Schematron rule att-datable-w3c-when should be there. It's perfectly reasonable to say that a date falls within a certain range, and also may, with specified certainty, fall on a particular date.

**Comment by ebeshero** [comment]
Just a heads-up, there's a confused peep about this now on the WWP listserv--maybe the first of many.

**Comment by sydb** [comment]
Given that #1487 has been closed, seems to me this one should be too.
