### ISSUE TITLE
`<taxonomy>` should allow both description elements and categories

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1415]
The content model of `<taxonomy>` currently allows  _either_ descriptive information about the taxonomy (`<desc>`, `<gloss>` etc.) _or_ a list of `<category>` elements, but not both. It's reasonable to want to describe your taxonomy in prose before defining it in `<category>`s. I believe the content model should be changed from this:

```
<content>
    <choice xmlns="http://relaxng.org/ns/structure/1.0">
      <zeroOrMore>
        <choice>
          <ref name="model.glossLike"/>
          <ref name="model.descLike"/>
        </choice>
      </zeroOrMore>
      <oneOrMore>
        <choice>
          <ref name="category"/>
          <ref name="taxonomy"/>
        </choice>
      </oneOrMore>
      <group>
        <group>
          <!-- this group a hack for odd2dtd processing -->
          <ref name="model.biblLike"/>
        </group>
        <zeroOrMore>
          <choice>
            <ref name="category"/>
            <ref name="taxonomy"/>
          </choice>
        </zeroOrMore>
      </group>
    </choice>
  </content>
```

to this:

```
<content>
    <choice xmlns="http://relaxng.org/ns/structure/1.0">
      <zeroOrMore>
        <choice>
          <ref name="model.glossLike"/>
          <ref name="model.descLike"/>
        </choice>
      </zeroOrMore>
      <oneOrMore>
        <choice>
          <ref name="category"/>
          <ref name="taxonomy"/>
        </choice>
      </oneOrMore>
      <group>
        <group>
          <!-- this group a hack for odd2dtd processing -->
          <ref name="model.biblLike"/>
        </group>
        <zeroOrMore>
          <choice>
            <ref name="model.glossLike"/>
            <ref name="model.descLike"/>
          </choice>
        </zeroOrMore>
        <zeroOrMore>
          <choice>
            <ref name="category"/>
            <ref name="taxonomy"/>
          </choice>
        </zeroOrMore>
      </group>
    </choice>
  </content>
```

Or perhaps to something simple that achieves the same result.

**Comment by lb42** [comment]
You don't say anything about the possibility of wanting to provide a bibliographic reference for your taxonomy, but I assume that this is still required. In which case, I'd suggest something much simpler, expressed in pure ODD as follows:
~~~~
<sequence>
<alternate maxOccurs="unlimited" minOccurs="0">
   <classRef key="model.glossLike"/>
   <classRef key="model.descLike"/>
   <classRef key="model.biblLike/>
</alternate>
<alternate maxOccurs="unlimited" minOccurs="0">
   <elementRef key="category"/>
   <elementRef key="taxonomy/>
</alternate>
</sequence>
~~~~
If we want to avoid the possibility of an empty &lt;taxonomy>,  this would need a schematron rule to say you have to supply something, but it's a lot easier to understand than either of the foregoing.

**Comment by martindholmes** [comment]
Agreed; we do need the option of bibliographic references in addition to descriptive stuff. The simpler formulation in pure ODD is nice. I think it's also reasonable to allow empty taxonomies.

**Comment by hcayless** [comment]
This seems fairly uncontroversial. Assigning to @tuurma to follow up on and implement.

**Comment by sydb** [comment]
Council sub-group believes this should be promoted from "needs discussion" to "Go". We also note that the "no empty <taxonomy>" constraint can be expressed in PureODD:

**Comment by sydb** [comment]
Turns out to be easy to represent the content in PureODD:
~~~~~
( a+, b* ) | ( a*, b+ )
~~~~~
Sadly, that is non-deterministic (or ambiguous). So although it is fine for PureODD or RELAX NG, we cannot generate a valid DTD or XSD from it. So it has to be written
~~~~~
( b+ | ( a+, b* ) )
~~~~~
instead. A bit more confusing to read, but should work just fine. Just addressed in commit e5f17fd115c75557c0bc671c7abf18c48da942f9.

**Comment by joeytakeda** [comment]
I'm working with @martindholmes on a project and we just tried to add <desc> to a taxonomy with <category>s but we're still getting errors. Has this change been implemented?

**Comment by lb42** [comment]
The content model of &lt;taxonomy> in the current release is
~~~~
<content>
 <alternate>
  <alternate minOccurs="0"
   maxOccurs="unbounded">
   <classRef key="model.glossLike"/>
   <classRef key="model.descLike"/>
  </alternate>
  <alternate minOccurs="1"
   maxOccurs="unbounded">
   <elementRef key="category"/>
   <elementRef key="taxonomy"/>
  </alternate>
  <sequence>
   <classRef key="model.biblLike"/>
   <alternate minOccurs="0"
    maxOccurs="unbounded">
    <elementRef key="category"/>
    <elementRef key="taxonomy"/>
   </alternate>
  </sequence>
 </alternate>
</content>
~~~~
which suggests that you would be able to to do what you want, provided you put the &lt;desc> elements before the &lt;category> elements. Could you post an example of what you're trying to do?

**Comment by joeytakeda** [comment]
I'm trying to use both `<desc>` and `<category>` which does not validate. 

The following code produces this validation error:

>  "element "category" not allowed here; expected the element end-tag or element "altIdent", "desc", "equiv" or "gloss"


```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
      <fileDesc>
         <titleStmt>
            <title type="main"/>
         </titleStmt>
         <publicationStmt>
           <p>Test.</p>
         </publicationStmt>
         <sourceDesc>
            <p>No source, born digital.</p>
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         <classDecl>
            <taxonomy>
               <desc>contains types of writing.</desc>
               <category>
                  <catDesc>prose</catDesc>
               </category>
               <category>
                  <catDesc>poetry</catDesc>
               </category>
            </taxonomy>
         </classDecl>
      </encodingDesc>
      <profileDesc>
         
      </profileDesc>
      <revisionDesc>
         <change/>
      </revisionDesc>
  </teiHeader>
<text>
      <body>
         <div></div>
      </body>
   </text>
</TEI>
```

**Comment by hcayless** [comment]
Re-opening so Council can investigate.

**Comment by hcayless** [comment]
It appears this might have been fixed in the 3.1.0 release. We can't reproduce the error. Can you check whether the problem still exists for you @joeytakeda?

**Comment by hcayless** [comment]
@sydb. If there's no followup within a few days, just close this.

**Comment by joeytakeda** [comment]
I can't reproduce the problem either. Thanks!
